---
-   name: Iterate over previously loaded user dictionary and create with password
    ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        home: "{{ (homePath, item.name) | path_join }}"
        create_home: false
        password: "{{item.pwhash}}"
    loop: "{{users}}"
    when: item.pwhash != "!!"
-   name: Iterate over previously loaded user dictionary and create without password
    ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        home: "{{ (homePath, item.name) | path_join }}"
        create_home: false
    loop: "{{users}}"
    when: item.pwhash == "!!"
